name: build

on: [push]

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  test:
    runs-on: ubuntu-latest
    #continue-on-error: ${{ matrix.experimental }}
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.0.5
      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run build test
        run: nimble install -Y nimjson
      - run: nimble install telebot
      - run: nimble install nimquery  
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: echo "$SUPER_SECRET" >> secret.key
      - name: Build app
        run: nimble build
      - run: mkdir -p builds
      - run: cp afvalbot builds/afvalbot
      - uses: actions/upload-artifact@v2
        with:
          name: afvalbot
          path: builds/afvalbot
